### ISSUE TITLE
The Kernel supports AOSP 7.1?

### ISSUE THREAD

**Issue by qiurigao** [AlexLartsev19/blood_m2note#1]
I'm compiling Meizu m2note AOSP 7.1 system
Need a kernel, the kernel can use?

**Comment by AlexLartsev19** [comment]
@qiurigao , yes, you can use this kernel source :)

**Comment by fooiskandar** [comment]
Btw why this kernel doesn't support flyme os ...

**Comment by fooiskandar** [comment]
Btw why this kernel doesn't support flyme os ...

**Comment by AlexLartsev19** [comment]
I don't know :new_moon_with_face:

**Comment by qiurigao** [comment]
@fooiskandar Flyme4.5 can work, flyme5 and flyme6 can't work, looks like.

Meizu is about to give us the meaning of the source code is 4.5, and later flyme5 and the kernel source code is not open to the public
